# Generated by Django 4.0.3 on 2022-11-04 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('applicant', '0001_initial'),
        ('position', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='position_applied',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='position.position', verbose_name='Position'),
        ),
    ]
