# Generated by Django 4.0.3 on 2022-03-28 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_slug'),
        ('position', '0001_initial'),
        ('applicant', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Apllicant',
            new_name='Applicant',
        ),
    ]
