# Generated by Django 4.0.3 on 2022-03-28 14:56

import apps.applicant.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0002_rename_apllicant_applicant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='cv',
            field=models.FileField(null=True, upload_to=apps.applicant.models.post_directory_path, verbose_name='CV'),
        ),
    ]
