# Generated by Django 4.0.3 on 2022-03-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0003_alter_applicant_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='country',
            field=models.CharField(max_length=50, verbose_name='Country'),
        ),
    ]
