# Generated by Django 4.0.3 on 2022-04-18 10:44

import apps.applicant.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0004_alter_applicant_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='comment',
            field=models.TextField(max_length=2000, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='cv',
            field=models.FileField(null=True, upload_to=apps.applicant.models.post_directory_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'csv', 'png', 'jpg'])], verbose_name='CV'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.CharField(choices=[('shortlisted', 'Shortlisted'), ('not_considered', 'Not considered'), ('interviewing', 'Interviewing'), ('rejected', 'Rejected'), ('for_future_consideration', 'For future consideration'), ('black_list', 'Black list')], default='shortlisted', max_length=60, verbose_name='Status'),
        ),
    ]
