# Generated by Django 4.0.3 on 2022-04-18 12:57

import apps.applicant.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0008_alter_applicant_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='cv',
            field=models.FileField(null=True, upload_to=apps.applicant.models.post_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'csv', 'png', 'jpg', 'doc', 'docx']), apps.applicant.models.validate_file_size], verbose_name='CV'),
        ),
    ]
