# Generated by Django 4.0.3 on 2022-11-04 13:23
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE users_user_user_permissions ADD company_id INTEGER REFERENCES company_company (id)"
        )
    ]
