# Generated by Django 4.0.3 on 2022-11-04 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_initial'),
        ('users', '0003_auto_20221104_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='active_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='Active Company'),
        ),
    ]
