# Generated by Django 4.0.3 on 2022-11-04 14:15

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(max_length=500, verbose_name='Description')),
                ('skill', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50, null=True), size=None, verbose_name='Skills')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Number')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='Company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
