# Generated by Django 4.0.3 on 2022-11-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('slug', models.SlugField(unique=True)),
                ('industry', models.CharField(max_length=50, verbose_name='Industry')),
                ('description', models.TextField(max_length=500, verbose_name='Description')),
                ('address', models.CharField(max_length=50, verbose_name='Address')),
                ('contacts', models.CharField(max_length=50, verbose_name='Contacts')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
